name: Deploy Frontend to Staging

on:
  push:
    branches:
      - main
    paths:
      - '**'  # Trigger on any file change

jobs:
  deploy:
    name: Deploy to EC2 (Staging)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Zip dist folder
        run: zip -r dist.zip dist

      - name: Upload dist.zip to EC2 (staging)
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          source: "dist.zip"
          target: "/tmp/"

      - name: Deploy via SSH and unzip on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          script: |
            sudo unzip -o /tmp/dist.zip -d ${{ secrets.FRONTEND_DEPLOY_PATH }}
            echo " Frontend deployed to staging!"
