name: Deploy Frontend to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Zip the dist folder
        run: zip -r dist.zip dist

      - name: Upload dist.zip to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          source: dist.zip
          target: /home/${{ secrets.SSH_USERNAME }}/

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          script: |
            cd /home/${{ secrets.SSH_USERNAME }}
            unzip -o dist.zip -d dist
            sudo rm -rf ${{ secrets.FRONTEND_DEPLOY_PATH }}/*
            sudo mv dist/* ${{ secrets.FRONTEND_DEPLOY_PATH }}/
            rm -rf dist dist.zip
